(global-set-key "\C-s" 'guoys-isearch-selection)
(global-set-key (kbd "C-c C-r") 'helm-recentf)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "C-h f") 'counsel-describe-function)
(global-set-key (kbd "C-h v") 'counsel-describe-variable)
(global-set-key (kbd "<f2>") 'open-my-init-file)
(global-set-key "\C-x\ \C-r" 'recentf-open-files)
(global-set-key (kbd "C-h C-f") 'find-function)
(global-set-key (kbd "C-h C-v") 'find-variable)
(global-set-key (kbd "C-h C-k") 'find-function-on-key)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c C-m") 'my-ecb-active-or-deactive)
(global-set-key (kbd "C-x b") 'helm-mini)
(provide 'init-keybindings)
